// File generated by FlutterFire CLI.
// Run `dart pub global activate flutterfire_cli` then `flutterfire configure`
// to replace this file with your project's Firebase configuration.
//
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      default:
        return android;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_WEB_API_KEY',
    appId: '1:000000000000:web:xxxxxxxxxxxx',
    messagingSenderId: '000000000000',
    projectId: 'kigali-city-services',
    authDomain: 'kigali-city-services.firebaseapp.com',
    storageBucket: 'kigali-city-services.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8MeS9Rxy6O6QFO5zhnPbuLIo8c2rp2Yc',
    appId: '1:719167142839:android:81c43806b4851b75508632',
    messagingSenderId: '719167142839',
    projectId: 'kigalicityservices',
    storageBucket: 'kigalicityservices.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA1o9hixLjUmyOe4oBHL2S_edYbMLLX4c',
    appId: '1:719167142839:ios:fc2467558b0397cd508632',
    messagingSenderId: '719167142839',
    projectId: 'kigalicityservices',
    storageBucket: 'kigalicityservices.firebasestorage.app',
    iosClientId: '719167142839-th3s4b7kmfjq6rol1mimlog4i2gvda30.apps.googleusercontent.com',
    iosBundleId: 'com.kigali.cityservices.kcs',
  );

}